### PR TITLE
Remove cluster context helpers

### PR DESCRIPTION
**Pull request by varshaprasad96**
Follow up of https://github.com/kcp-dev/logicalcluster/pull/10

TODO: bump go.mod to use latest commit after the above PR is merged.

### CODE REVIEW

**Comment by ncdc** [comment]
@varshaprasad96 you can do the go.mod bump now 😄

**Comment by varshaprasad96** [comment]
@ncdc @sttts This is ready to merge.

**Review by ncdc — APPROVED** [review]

**Pull request merged**
